version: 2

references:
  workspace: &workspace
    ~/browser-open-share

  config_android: &config_android
    working_directory: *workspace
    docker:
      - image: circleci/android:api-29
    environment:
      TERM: dumb

  cache_key: &cache_key
    key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
  restore_cache: &restore_cache
    restore_cache:
      <<: *cache_key
  save_cache: &save_cache
    save_cache:
      <<: *cache_key
      paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper

jobs:
  build:
    <<: *config_android

    steps:
      - checkout
      - *restore_cache

      - run:
          name: Compile
          command: ./gradlew assemble --no-daemon
      - store_artifacts:
          path: app/build/outputs

      - run:
          name: JVM Tests & Lint
          command: ./gradlew check --no-daemon
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/test-results
      - store_artifacts:
          path: app/build/reports/lint-results.html
      - store_test_results:
          path: app/build/reports

      - *save_cache

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
